import shutil
from pathlib import Path
from datetime import datetime
import json

class BubblyExporter:
    def __init__(self, messages, media_folder, output_folder, metadata, templates_folder):
        self.messages = messages
        self.media_folder = Path(media_folder)
        self.output_folder = Path(output_folder)
        self.metadata = metadata
        self.templates_folder = Path(templates_folder)
        self.output_folder.mkdir(parents=True, exist_ok=True)
        (self.output_folder / "media").mkdir(exist_ok=True)

    # ----------------------
    # Load template file
    # ----------------------
    def _load_template(self, file_name: str):
        path = self.templates_folder / file_name
        if not path.exists():
            raise FileNotFoundError(f"Template not found: {path}")
        return path.read_text(encoding="utf-8")

    # ----------------------
    # Copy media files
    # ----------------------
    def _copy_media(self):
        copied_count = 0
        for msg in self.messages:
            if msg.get("media"):
                src = self.media_folder / msg["media"]
                if src.exists():
                    dest = self.output_folder / "media" / msg["media"]
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy(src, dest)
                    copied_count += 1
        return copied_count

    # ----------------------
    # Export messages as JSON
    # ----------------------
    def _export_json(self):
        json_path = self.output_folder / "chat.json"
        messages_json = []
        for msg in self.messages:
            messages_json.append({
                "sender": msg["sender"],
                "content": msg["content"],
                "timestamp": msg["timestamp"],
                "media": msg.get("media"),
                "is_owner": msg.get("is_owner"),
                "is_group_chat": self.metadata.get("is_group_chat", False)
            })
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(messages_json, f, ensure_ascii=False, indent=2)
        return json_path.name

    # ----------------------
    # Export HTML
    # ----------------------
    def export_html(self, output_html_name="chat.html"):
        copied_count = self._copy_media()
        json_file = self._export_json()
        generated_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # ----------------------
        # Metadata header
        # ----------------------
        meta = self.metadata
        header_lines = [
            ("Report generated by", meta.get("user")),
            ("Report generated at", generated_time),
            ("Case number", meta.get("case")),
            ("Chat name", meta.get("chat_name")),
            ("Source", meta.get("source")),
            ("WhatsApp account name", meta.get("wa_account_name")),
            ("WhatsApp account number", meta.get("wa_account_number")),
            ("Telegram account name", meta.get("tg_account_name")),
            ("Group chat", meta.get("is_group_chat")),
            ("Platform", meta.get("platform")),
            ("Media files copied", copied_count),
        ]
        header_html = [
            '<div class="report-header" style="padding:10px; margin-bottom:20px; background:#ddd; border-radius:10px;">'
        ]
        for label, value in header_lines:
            if value is None:
                continue
            header_html.append(f"<p><strong>{label}:</strong> {value}</p>")
        header_html.append("</div>")
        header_html = "\n".join(header_html)

        # ----------------------
        # Load templates
        # ----------------------
        html_template = self._load_template("chat.html")
        css_content = self._load_template("style.css")
        js_content = self._load_template("chat.js")

        # ----------------------
        # Inline CSS & JS
        # ----------------------
        html_content = html_template.replace(
            '<link rel="stylesheet" href="style.css">',
            f"<style>{css_content}</style>"
        ).replace(
            '<script src="chat.js"></script>',
            f"<script>{js_content}</script>"
        ).replace(
            "{{header}}", header_html
        ).replace(
            #"{{messages_json_path}}", json_file
            "{{messages_json_content}}", json.dumps(self.messages, ensure_ascii=False)
        )

        # ----------------------
        # Write final HTML
        # ----------------------
        output_html_path = self.output_folder / output_html_name
        with open(output_html_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        print(f"HTML saved to {output_html_path} with inline CSS/JS")
