import html
import shutil
from datetime import datetime
from pathlib import Path


def _copy_index_logo(output_folder, logo_path):
    if not logo_path:
        return None
    source = Path(logo_path)
    if not source.exists() or not source.is_file():
        return None
    branding_dir = Path(output_folder) / "branding"
    branding_dir.mkdir(parents=True, exist_ok=True)
    ext = source.suffix or ".png"
    target_name = f"branding_logo{ext.lower()}"
    target = branding_dir / target_name
    shutil.copy(source, target)
    return f"branding/{target_name}"


def write_split_index(output_folder, safe_case, reports, case_value, creator=None, logo_path=None, created_at=None):
    if not reports:
        return
    title = f"{case_value} - Chats" if case_value else "Bubbly Chat Index"
    created_text = created_at or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    logo_rel_path = _copy_index_logo(output_folder, logo_path)
    logo_html = ""
    if logo_rel_path:
        logo_html = (
            '<div class="branding-logo">'
            f'<img src="{html.escape(logo_rel_path)}" alt="Brand logo">'
            "</div>"
        )
    rows = []
    for entry in reports:
        chat_escaped = html.escape(entry["chat_name"])
        file_escaped = html.escape(entry["file_name"])
        href_escaped = html.escape(entry.get("file_href") or entry["file_name"])
        rows.append(
            "<tr>"
            f"<td>{chat_escaped}</td>"
            f"<td>{entry['message_count']}</td>"
            f"<td>{entry['media_count']}</td>"
            f"<td><a href=\"{href_escaped}\">{file_escaped}</a></td>"
            "</tr>"
        )
    table_rows = "\n".join(rows)
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{html.escape(title)}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; background: #f8f8f8; color: #222; }}
    .branding-logo {{ margin: 0 0 12px 0; width: min(30vw, 220px); height: min(12vh, 90px); }}
    .branding-logo img {{ width: 100%; height: 100%; object-fit: contain; display: block; }}
    h1 {{ margin: 0 0 12px 0; }}
    p {{ margin: 0 0 8px 0; color: #555; }}
    .meta {{ margin: 0 0 18px 0; color: #444; }}
    table {{ width: 100%; border-collapse: collapse; background: #fff; }}
    th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
    th {{ background: #f0f0f0; }}
    a {{ color: #1a5fd0; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    @media (max-width: 700px) {{
      .branding-logo {{ width: min(55vw, 180px); height: min(10vh, 72px); }}
    }}
  </style>
</head>
<body>
  {logo_html}
  <h1>{html.escape(title)}</h1>
  <p>Generated by Bubbly. Open a chat file below.</p>
  <p class="meta"><strong>Creator:</strong> {html.escape(str(creator or "-"))}<br><strong>Creation date:</strong> {html.escape(created_text)}</p>
  <table>
    <thead>
      <tr><th>Chat</th><th>Messages</th><th>Media files</th><th>File</th></tr>
    </thead>
    <tbody>
{table_rows}
    </tbody>
  </table>
</body>
</html>
"""
    index_path = output_folder / f"{safe_case}_index.html"
    index_path.write_text(html_content, encoding="utf-8")
